"""Operation handlers — the thin glue from the contract to domain services.

Layer: api.
Constitutional home: 12_API §2 (handlers contain dispatch-to-domain only; an
`if` about domain semantics here is a defect), §7 (commands), §8 (queries),
§12 (explainability). Each handler is built with its domain dependencies
bound at the composition root; the dispatcher supplies (context, params).

task.create follows EB-004 through the bus: the task.created event is
published on the truth the task domain owns (principal `kernel:tasks`,
EB-010) with the request's correlation_id threaded through, and the state
commit is the bus's step 3.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Any, Callable

from kang.api.dispatch import Handler, HandlerContext
from kang.api.errors import ApiError
from kang.api.registry import registry_snapshot
from kang.domain.deadlines import (
    DeadlineDraft,
    DeadlineValidationError,
    create_deadline,
    deadline_event_payload,
    due_lead_thresholds,
    mark_alerted,
)
from kang.domain.planner import (
    PlanInputs,
    build_plan,
    plan_generated_payload,
)
from kang.domain.ports.calendar_store import CalendarStore
from kang.domain.ports.clock import Clock
from kang.domain.ports.deadline_store import Deadline, DeadlineStore
from kang.domain.ports.eventlog import EventEnvelope
from kang.domain.ports.invocation import InvocationNotFound, InvocationStore
from kang.domain.ports.notification_store import (
    NotificationNotFoundError,
    NotificationStore,
)
from kang.domain.ports.task_store import TaskNotFoundError, TaskStore
from kang.domain.tasks import (
    TaskDraft,
    TaskValidationError,
    create_task,
    task_event_payload,
)
from kang.kernel.audit.service import AuditService
from kang.kernel.bus.bus import EventBus

__all__ = [
    "make_deadline_create_handler",
    "make_deadline_sweep_handler",
    "make_explain_invocation_handler",
    "make_explain_stub_handler",
    "make_notification_ack_handler",
    "make_plan_generate_handler",
    "PlannerDeps",
    "make_registry_get_handler",
    "make_task_create_handler",
    "make_task_get_handler",
]

TASKS_PRINCIPAL = "kernel:tasks"  # the domain that owns task truth (EB-010)
DEADLINES_PRINCIPAL = "kernel:deadlines"  # owns deadline truth (EB-010)
PLANNER_PRINCIPAL = "kernel:planner"  # announces plan.generated (EB-010)


def make_registry_get_handler() -> Handler:
    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        return registry_snapshot()

    return handler


def make_task_create_handler(
    bus: EventBus,
    task_store: TaskStore,
    clock: Clock,
    new_id: Callable[[], str],
    device_id: str,
) -> Handler:
    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        title = params.get("title")
        if not isinstance(title, str) or not title.strip():
            raise ApiError("invalid_request", "task.create requires a 'title'")
        try:
            task = create_task(
                TaskDraft(title=title, priority=int(params.get("priority", 3))),
                task_id=new_id(),
                clock=clock,
                device_id=device_id,
            )
        except (TaskValidationError, ValueError) as exc:
            raise ApiError("invalid_request", str(exc)) from exc
        envelope = EventEnvelope(
            event_id=new_id(),
            type="task.created",
            occurred_at=task.created_at.isoformat(),
            principal=TASKS_PRINCIPAL,
            correlation_id=context.correlation_id,
            device_id=device_id,
            payload=task_event_payload(task),
            recovery_grade=True,
            entity_refs=({"kind": "task", "id": task.id},),
        )
        bus.publish(envelope, commit_state=lambda: task_store.create(task))
        return {"task_id": task.id, "revision": task.revision}

    return handler


def make_task_get_handler(task_store: TaskStore) -> Handler:
    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        task_id = params.get("id")
        if not isinstance(task_id, str):
            raise ApiError("invalid_request", "task.get requires an 'id'")
        try:
            task = task_store.get(task_id)
        except TaskNotFoundError as exc:
            raise ApiError("not_found", f"no task {task_id}") from exc
        return {
            "id": task.id,
            "title": task.title,
            "status": task.status,
            "priority": task.priority,
            "revision": task.revision,
        }

    return handler


@dataclass(frozen=True)
class _AlertIds:
    """The ids and stamps one alert's two envelopes share (11 §4: beyond a
    few parameters, a dataclass). Generated by the caller so the sweep stays
    the only place the id source is read."""

    mutation_id: str
    fact_id: str
    occurred_at: str
    device_id: str


def _deadline_envelope(
    deadline, *, event_id: str, event_type: str, correlation_id: str, device_id: str
) -> EventEnvelope:
    """One deadline truth-mutation envelope. Recovery-grade with the full
    row (ADR-004): a lost write must replay exactly."""
    return EventEnvelope(
        event_id=event_id,
        type=event_type,
        occurred_at=deadline.updated_at.isoformat(),
        principal=DEADLINES_PRINCIPAL,
        correlation_id=correlation_id,
        device_id=device_id,
        payload=deadline_event_payload(deadline),
        recovery_grade=True,
        entity_refs=({"kind": "deadline", "id": deadline.id},),
    )


def make_deadline_create_handler(
    bus: EventBus,
    deadline_store: DeadlineStore,
    clock: Clock,
    new_id: Callable[[], str],
    device_id: str,
) -> Handler:
    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        try:
            deadline = create_deadline(
                DeadlineDraft(
                    title=params.get("title", ""),
                    at=params.get("at", ""),
                    kind=params.get("kind", "custom"),
                    competition_id=params.get("competition_id"),
                    project_id=params.get("project_id"),
                ),
                deadline_id=new_id(),
                clock=clock,
                device_id=device_id,
            )
        except DeadlineValidationError as exc:
            raise ApiError("invalid_request", str(exc)) from exc
        bus.publish(
            _deadline_envelope(
                deadline,
                event_id=new_id(),
                event_type="deadline.created",
                correlation_id=context.correlation_id,
                device_id=device_id,
            ),
            commit_state=lambda: deadline_store.create(deadline),
        )
        return {"deadline_id": deadline.id, "revision": deadline.revision}

    return handler


# ORDERING RULING — ADR-004 left this open to be decided against real code;
# decided here. One `tracked → alerted` flip publishes **two** events, in a
# fixed order:
#
#   1. `deadline.updated`     — carries the state commit. Recovery-grade,
#      full row. It is the redo record: EB-003 REQUIRES recovery-grade for
#      deadline truth mutations, and `alerted` is truth.
#   2. `deadline.approaching` — the trigger fact, `causation_id` set to
#      (1)'s event_id, committing no state of its own.
#
# Why not one event. Collapsing into `deadline.approaching` alone leaves the
# mutation with no recovery-grade redo record (EB-003 violation), and that
# type cannot itself be recovery-grade because EB-008 rule 2 states it
# "changes no row". Collapsing into `deadline.updated` alone forces the
# notifier to subscribe to a generic update and re-derive "is this
# approaching?" from status — domain semantics leaking into a subscriber,
# and contradicting 05 Appendix F, which names `deadline.approaching` as the
# notifier's and planner's trigger.
#
# Why this order. The commit must be durable before the fact is announced.
# Announcing first means a crash in between leaves a notification for a
# deadline still marked `tracked`, which the next sweep re-alerts — the
# duplicate 09_UI §9's 24h re-notification rule forbids.
def _publish_deadline_alert(
    bus: EventBus,
    store: DeadlineStore,
    alerted: Deadline,
    context: HandlerContext,
    ids: _AlertIds,
) -> None:
    bus.publish(
        _deadline_envelope(
            alerted,
            event_id=ids.mutation_id,
            event_type="deadline.updated",
            correlation_id=context.correlation_id,
            device_id=ids.device_id,
        ),
        commit_state=lambda: store.update(alerted),
    )
    bus.publish(
        EventEnvelope(
            event_id=ids.fact_id,
            type="deadline.approaching",
            occurred_at=ids.occurred_at,
            principal=DEADLINES_PRINCIPAL,
            correlation_id=context.correlation_id,
            causation_id=ids.mutation_id,  # 15 §5.1: the direct parent
            device_id=ids.device_id,
            payload={
                "deadline_id": alerted.id,
                "title": alerted.title,
                "at": alerted.at,
            },
            recovery_grade=False,
            entity_refs=({"kind": "deadline", "id": alerted.id},),
        ),
        # No state of its own: the mutation above already committed. A pure
        # fact's whole existence IS the event (EB-008 rule 2).
        commit_state=lambda: None,
    )


def make_deadline_sweep_handler(
    bus: EventBus,
    deadline_store: DeadlineStore,
    clock: Clock,
    new_id: Callable[[], str],
    device_id: str,
) -> Handler:
    """The lead-time sweep (FR-031): every tracked deadline whose lead
    threshold has been crossed transitions `tracked → alerted` and announces
    itself. See the ordering ruling above `_publish_deadline_alert`."""

    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        now = clock.now()
        alerted: list[str] = []
        for deadline in deadline_store.active():
            if not due_lead_thresholds(deadline, now):
                continue
            transitioned = mark_alerted(deadline)
            _publish_deadline_alert(
                bus,
                deadline_store,
                transitioned,
                context,
                _AlertIds(
                    mutation_id=new_id(),
                    fact_id=new_id(),
                    occurred_at=now.isoformat(),
                    device_id=device_id,
                ),
            )
            alerted.append(transitioned.id)
        return {"alerted": alerted, "count": len(alerted)}

    return handler


@dataclass(frozen=True)
class PlannerDeps:
    """The Planner handler's collaborators (11 §4)."""

    bus: EventBus
    tasks: TaskStore
    deadlines: DeadlineStore
    calendar: CalendarStore
    clock: Clock
    new_id: Callable[[], str]
    device_id: str


def _stamp_quests(deps: PlannerDeps, plan, correlation_id: str) -> list[str]:
    """Commit the plan's durable half: `plan_date` on each quest.

    This is the mutation-first half of the same ordering discipline the
    deadline sweep uses. Each stamp is a task truth mutation, so it rides
    the recovery-grade `task.updated` (EB-003); `plan.generated` is
    published only after they all commit, because announcing a plan whose
    tasks are not yet stamped would advertise state that a crash could
    erase.
    """
    stamped: list[str] = []
    for quest in plan.quests:
        if quest.plan_date == plan.plan_date:
            continue  # idempotent: re-running a slot re-stamps nothing
        updated = replace(quest, plan_date=plan.plan_date)
        deps.bus.publish(
            EventEnvelope(
                event_id=deps.new_id(),
                type="task.updated",
                occurred_at=deps.clock.now().isoformat(),
                principal=TASKS_PRINCIPAL,
                correlation_id=correlation_id,
                device_id=deps.device_id,
                payload=task_event_payload(
                    replace(updated, revision=updated.revision + 1)
                ),
                recovery_grade=True,
                entity_refs=({"kind": "task", "id": quest.id},),
            ),
            commit_state=lambda t=updated: deps.tasks.update(t),
        )
        stamped.append(quest.id)
    return stamped


def make_plan_generate_handler(deps: PlannerDeps) -> Handler:
    """`plan.generate` — the deterministic morning plan (FR-001).

    Zero model calls, by construction: it reads P0 data and calls the pure
    `build_plan`. This is the release-blocking degradation floor (05 §16),
    built before any model exists to fall back from (18 §7.6).
    """

    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        plan_date = params.get("plan_date") or deps.clock.now().date().isoformat()
        plan = build_plan(
            PlanInputs(
                plan_date=plan_date,
                tasks=tuple(deps.tasks.plannable()),
                deadlines=tuple(deps.deadlines.active()),
                calendar=tuple(deps.calendar.events_on(plan_date)),
            )
        )
        stamped = _stamp_quests(deps, plan, context.correlation_id)
        mutation_id = deps.new_id()
        deps.bus.publish(
            EventEnvelope(
                event_id=mutation_id,
                type="plan.generated",
                occurred_at=deps.clock.now().isoformat(),
                principal=PLANNER_PRINCIPAL,
                correlation_id=context.correlation_id,
                device_id=deps.device_id,
                payload=plan_generated_payload(plan),
                recovery_grade=False,  # derived state (ADR-004)
                entity_refs=tuple(
                    {"kind": "task", "id": quest.id} for quest in plan.quests
                ),
            ),
            # The quests' stamps already committed above; this announces the
            # plan, it does not carry it.
            commit_state=lambda: None,
        )
        return {
            "plan_date": plan.plan_date,
            "quest_ids": [t.id for t in plan.quests],
            "deadline_ids": [d.id for d in plan.deadlines],
            "calendar_event_ids": [e.provider_event_id for e in plan.calendar],
            "estimated_minutes": plan.estimated_minutes,
            "deferred_count": plan.deferred_count,
            "stamped": stamped,
        }

    return handler


def make_notification_ack_handler(
    notification_store: NotificationStore, clock: Clock
) -> Handler:
    """`notification.ack` (12 §13): acking is a command, and it is additive
    — it stamps `acked_at` and never deletes history."""

    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        notification_id = params.get("id")
        if not isinstance(notification_id, str) or not notification_id:
            raise ApiError("invalid_request", "notification.ack requires an 'id'")
        try:
            acked = notification_store.ack(notification_id, clock.now())
        except NotificationNotFoundError as exc:
            raise ApiError(
                "not_found", f"no notification {notification_id}"
            ) from exc
        return {"id": acked.id, "state": acked.state}

    return handler


def make_explain_invocation_handler(
    invocations: InvocationStore, audit: AuditService
) -> Handler:
    """explain.invocation (12 §12): reconstruct from PERMANENT storage —
    the invocation row + the audit chain — by correlation_id. Never the
    event log (its 90-day retention would break the ≥180-day guarantee)."""

    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        target = params.get("correlation_id")
        if not isinstance(target, str) or not target:
            raise ApiError(
                "invalid_request", "explain.invocation requires a 'correlation_id'"
            )
        try:
            invocation = invocations.by_correlation(target)
        except InvocationNotFound as exc:
            raise ApiError(
                "not_found", f"no invocation for correlation_id {target}"
            ) from exc
        chain = [
            {
                "action": record.entry.action,
                "principal": record.entry.principal,
                "at": record.entry.at,
                "details": record.entry.details,
            }
            for record in audit.records_for_correlation(target)
        ]
        return {
            "correlation_id": target,
            "trigger": invocation.trigger,
            "operation": invocation.operation,
            "principal": invocation.principal,
            "kind": invocation.kind,
            "manifest": invocation.manifest,  # None for non-agent operations
            "started": invocation.started,
            "finished": invocation.finished,
            "outcome": invocation.outcome,
            "chain": chain,
            "reconstructed_from": "invocation + audit (permanent storage)",
        }

    return handler


def make_explain_stub_handler(kind: str) -> Handler:
    """explain.plan_item/notification/suggestion/memory (12 §12): registered
    now; their subjects (plans, notifications, memory) arrive at M5/Phase 2.
    Until then they honestly return not_found — never a synthesized narrative
    (A4)."""

    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        raise ApiError(
            "not_found",
            f"no {kind} to explain yet — its subject arrives in a later milestone",
        )

    return handler
