"""deadline.create / deadline.sweep / deadline.list handlers.

Layer: api.
Constitutional home: 12_API §2/§7/§8, ADR-004 (deadline.created/.updated/
.approaching — the ordering ruling below is that ADR's own open question,
decided against real code here, per its Consequences section).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable

from kang.api.dispatch import Handler, HandlerContext
from kang.api.errors import ApiError
from kang.domain.deadlines import (
    DeadlineDraft,
    DeadlineValidationError,
    create_deadline,
    deadline_event_payload,
    due_lead_thresholds,
    mark_alerted,
)
from kang.domain.ports.clock import Clock
from kang.domain.ports.deadline_store import Deadline, DeadlineStore
from kang.domain.ports.eventlog import EventEnvelope
from kang.kernel.bus.bus import EventBus

__all__ = [
    "DEADLINES_PRINCIPAL",
    "make_deadline_create_handler",
    "make_deadline_list_handler",
    "make_deadline_sweep_handler",
]

DEADLINES_PRINCIPAL = "kernel:deadlines"  # owns deadline truth (EB-010)


def make_deadline_list_handler(deadline_store: DeadlineStore) -> Handler:
    """`deadline.list` (added 2026-08-05, dashboard Zone 2, 09_UI §4): every
    `tracked` deadline, soonest first — `DeadlineStore.active()`'s existing
    contract, already relied on by `deadline_sweep` and `plan.generate`
    below. No new domain logic; this handler is pure API-layer exposure,
    following `task.get`'s hand-picked-field convention rather than the
    full `deadline_event_payload` shape (that shape is for event replay)."""

    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        return {
            "deadlines": [
                {
                    "id": d.id,
                    "title": d.title,
                    "at": d.at,
                    "kind": d.kind,
                    "status": d.status,
                    "competition_id": d.competition_id,
                    "project_id": d.project_id,
                }
                for d in deadline_store.active()
            ]
        }

    return handler


@dataclass(frozen=True)
class _AlertIds:
    """The ids and stamps one alert's two envelopes share (11 §4: beyond a
    few parameters, a dataclass). Generated by the caller so the sweep stays
    the only place the id source is read."""

    mutation_id: str
    fact_id: str
    occurred_at: str
    device_id: str


def _deadline_envelope(
    deadline, *, event_id: str, event_type: str, correlation_id: str, device_id: str
) -> EventEnvelope:
    """One deadline truth-mutation envelope. Recovery-grade with the full
    row (ADR-004): a lost write must replay exactly."""
    return EventEnvelope(
        event_id=event_id,
        type=event_type,
        occurred_at=deadline.updated_at.isoformat(),
        principal=DEADLINES_PRINCIPAL,
        correlation_id=correlation_id,
        device_id=device_id,
        payload=deadline_event_payload(deadline),
        recovery_grade=True,
        entity_refs=({"kind": "deadline", "id": deadline.id},),
    )


def make_deadline_create_handler(
    bus: EventBus,
    deadline_store: DeadlineStore,
    clock: Clock,
    new_id: Callable[[], str],
    device_id: str,
) -> Handler:
    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        try:
            deadline = create_deadline(
                DeadlineDraft(
                    title=params.get("title", ""),
                    at=params.get("at", ""),
                    kind=params.get("kind", "custom"),
                    competition_id=params.get("competition_id"),
                    project_id=params.get("project_id"),
                ),
                deadline_id=new_id(),
                clock=clock,
                device_id=device_id,
            )
        except DeadlineValidationError as exc:
            raise ApiError("invalid_request", str(exc)) from exc
        bus.publish(
            _deadline_envelope(
                deadline,
                event_id=new_id(),
                event_type="deadline.created",
                correlation_id=context.correlation_id,
                device_id=device_id,
            ),
            commit_state=lambda: deadline_store.create(deadline),
        )
        return {"deadline_id": deadline.id, "revision": deadline.revision}

    return handler


# ORDERING RULING — ADR-004 left this open to be decided against real code;
# decided here. One `tracked → alerted` flip publishes **two** events, in a
# fixed order:
#
#   1. `deadline.updated`     — carries the state commit. Recovery-grade,
#      full row. It is the redo record: EB-003 REQUIRES recovery-grade for
#      deadline truth mutations, and `alerted` is truth.
#   2. `deadline.approaching` — the trigger fact, `causation_id` set to
#      (1)'s event_id, committing no state of its own.
#
# Why not one event. Collapsing into `deadline.approaching` alone leaves the
# mutation with no recovery-grade redo record (EB-003 violation), and that
# type cannot itself be recovery-grade because EB-008 rule 2 states it
# "changes no row". Collapsing into `deadline.updated` alone forces the
# notifier to subscribe to a generic update and re-derive "is this
# approaching?" from status — domain semantics leaking into a subscriber,
# and contradicting 05 Appendix F, which names `deadline.approaching` as the
# notifier's and planner's trigger.
#
# Why this order. The commit must be durable before the fact is announced.
# Announcing first means a crash in between leaves a notification for a
# deadline still marked `tracked`, which the next sweep re-alerts — the
# duplicate 09_UI §9's 24h re-notification rule forbids.
def _publish_deadline_alert(
    bus: EventBus,
    store: DeadlineStore,
    alerted: Deadline,
    context: HandlerContext,
    ids: _AlertIds,
) -> None:
    bus.publish(
        _deadline_envelope(
            alerted,
            event_id=ids.mutation_id,
            event_type="deadline.updated",
            correlation_id=context.correlation_id,
            device_id=ids.device_id,
        ),
        commit_state=lambda: store.update(alerted),
    )
    bus.publish(
        EventEnvelope(
            event_id=ids.fact_id,
            type="deadline.approaching",
            occurred_at=ids.occurred_at,
            principal=DEADLINES_PRINCIPAL,
            correlation_id=context.correlation_id,
            causation_id=ids.mutation_id,  # 15 §5.1: the direct parent
            device_id=ids.device_id,
            payload={
                "deadline_id": alerted.id,
                "title": alerted.title,
                "at": alerted.at,
            },
            recovery_grade=False,
            entity_refs=({"kind": "deadline", "id": alerted.id},),
        ),
        # No state of its own: the mutation above already committed. A pure
        # fact's whole existence IS the event (EB-008 rule 2).
        commit_state=lambda: None,
    )


def make_deadline_sweep_handler(
    bus: EventBus,
    deadline_store: DeadlineStore,
    clock: Clock,
    new_id: Callable[[], str],
    device_id: str,
) -> Handler:
    """The lead-time sweep (FR-031): every tracked deadline whose lead
    threshold has been crossed transitions `tracked → alerted` and announces
    itself. See the ordering ruling above `_publish_deadline_alert`."""

    def handler(context: HandlerContext, params: dict[str, Any]) -> dict[str, Any]:
        now = clock.now()
        alerted: list[str] = []
        for deadline in deadline_store.active():
            if not due_lead_thresholds(deadline, now):
                continue
            transitioned = mark_alerted(deadline)
            _publish_deadline_alert(
                bus,
                deadline_store,
                transitioned,
                context,
                _AlertIds(
                    mutation_id=new_id(),
                    fact_id=new_id(),
                    occurred_at=now.isoformat(),
                    device_id=device_id,
                ),
            )
            alerted.append(transitioned.id)
        return {"alerted": alerted, "count": len(alerted)}

    return handler
